/**
 * Generate src/build-info.ts with build metadata.
 * Run at Docker build time with env vars from CI.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, "..", "src");
const pkgPath = path.join(__dirname, "..", "package.json");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
const gitCommit = process.env.GIT_COMMIT || "dev";
const gitBranch = process.env.GIT_BRANCH || "dev";
const buildTime = process.env.BUILD_TIME || new Date().toISOString();

const output = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const buildInfo = {
  version: ${JSON.stringify(pkg.version)},
  git_commit: ${JSON.stringify(gitCommit)},
  git_branch: ${JSON.stringify(gitBranch)},
  build_time: ${JSON.stringify(buildTime)},
};
`;

fs.writeFileSync(path.join(srcDir, "build-info.ts"), output);
console.log(`Generated build-info.ts: v${pkg.version} ${gitCommit} (${gitBranch})`);
